version: "3.7"

services:
  db:
    build: ./database
    container_name: postgresql
    restart: always
    environment:
        POSTGRES_PASSWORD: example
    ports:
        - "5433:5432"
    volumes:
      - postgrescheduleapp:/var/lib/postgresql/data
    networks:
      - scheduleapp

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: example@domain.com
      PGADMIN_DEFAULT_PASSWORD: example
    ports:
      - "81:80"
    networks:
      - scheduleapp

  flask:
    build: ./flask
    container_name: flask
    restart: always
    environment:
      - DATABASE_NAME=scheduleapp
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=example
      - DATABASE_PORT=5432
      - DATABASE_HOST=db
    expose:
      - 8080
    depends_on:
      - "db"
      - "nginx"
    networks:
      - scheduleapp 

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    networks:
      - scheduleapp 

networks:
  scheduleapp:
    driver: bridge

volumes:
  postgrescheduleapp:
    driver: local
   
     